source("./TestClose.R")
source("./TestConnect.R")
source("./TestRunScalar.R")
source("./TestRunPair.R")
source("./TestRunVector.R")
source("./TestRunSet.R")
source("./TestRunMatrix.R")
source("./TestRunTable.R")
source("./TestRpc.R")
source("./TestUploadScalar.R")
source("./TestUploadVector.R")
source("./TestUploadMatrix.R")
source("./TestUploadTable.R")

. <- test$run()
. <- test$testResult()