// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Connect
bool Connect(String host, int port);
RcppExport SEXP _RDolphinDB_Connect(SEXP hostSEXP, SEXP portSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type host(hostSEXP);
    Rcpp::traits::input_parameter< int >::type port(portSEXP);
    rcpp_result_gen = Rcpp::wrap(Connect(host, port));
    return rcpp_result_gen;
END_RCPP
}
// RunScript
int RunScript(String script);
RcppExport SEXP _RDolphinDB_RunScript(SEXP scriptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type script(scriptSEXP);
    rcpp_result_gen = Rcpp::wrap(RunScript(script));
    return rcpp_result_gen;
END_RCPP
}
// RunFunctionInit
bool RunFunctionInit(String func, int arg_size);
RcppExport SEXP _RDolphinDB_RunFunctionInit(SEXP funcSEXP, SEXP arg_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type func(funcSEXP);
    Rcpp::traits::input_parameter< int >::type arg_size(arg_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(RunFunctionInit(func, arg_size));
    return rcpp_result_gen;
END_RCPP
}
// RunUploadInit
bool RunUploadInit(CharacterVector R_keys);
RcppExport SEXP _RDolphinDB_RunUploadInit(SEXP R_keysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type R_keys(R_keysSEXP);
    rcpp_result_gen = Rcpp::wrap(RunUploadInit(R_keys));
    return rcpp_result_gen;
END_RCPP
}
// ReceiveHeader
bool ReceiveHeader();
RcppExport SEXP _RDolphinDB_ReceiveHeader() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ReceiveHeader());
    return rcpp_result_gen;
END_RCPP
}
// ReceiveEntity
int ReceiveEntity();
RcppExport SEXP _RDolphinDB_ReceiveEntity() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ReceiveEntity());
    return rcpp_result_gen;
END_RCPP
}
// UploadVectorDateTime
void UploadVectorDateTime(NumericVector R_vec, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadVectorDateTime(SEXP R_vecSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type R_vec(R_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadVectorDateTime(R_vec, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadScalarDateTime
void UploadScalarDateTime(String date_time_str);
RcppExport SEXP _RDolphinDB_UploadScalarDateTime(SEXP date_time_strSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type date_time_str(date_time_strSEXP);
    UploadScalarDateTime(date_time_str);
    return R_NilValue;
END_RCPP
}
// UploadVectorDate
void UploadVectorDate(DateVector R_vec, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadVectorDate(SEXP R_vecSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type R_vec(R_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadVectorDate(R_vec, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadScalarDate
void UploadScalarDate(String date_str);
RcppExport SEXP _RDolphinDB_UploadScalarDate(SEXP date_strSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type date_str(date_strSEXP);
    UploadScalarDate(date_str);
    return R_NilValue;
END_RCPP
}
// UploadTableBasic
void UploadTableBasic(int row, int clm, CharacterVector Colnames);
RcppExport SEXP _RDolphinDB_UploadTableBasic(SEXP rowSEXP, SEXP clmSEXP, SEXP ColnamesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type clm(clmSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type Colnames(ColnamesSEXP);
    UploadTableBasic(row, clm, Colnames);
    return R_NilValue;
END_RCPP
}
// UploadMatrixNULL
void UploadMatrixNULL(int row, int clm);
RcppExport SEXP _RDolphinDB_UploadMatrixNULL(SEXP rowSEXP, SEXP clmSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type clm(clmSEXP);
    UploadMatrixNULL(row, clm);
    return R_NilValue;
END_RCPP
}
// UploadMatrixLableFlag
void UploadMatrixLableFlag(int flag);
RcppExport SEXP _RDolphinDB_UploadMatrixLableFlag(SEXP flagSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type flag(flagSEXP);
    UploadMatrixLableFlag(flag);
    return R_NilValue;
END_RCPP
}
// UploadMatrixFlag
void UploadMatrixFlag(int flag);
RcppExport SEXP _RDolphinDB_UploadMatrixFlag(SEXP flagSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type flag(flagSEXP);
    UploadMatrixFlag(flag);
    return R_NilValue;
END_RCPP
}
// UploadMatrixBool
void UploadMatrixBool(LogicalMatrix R_mtx, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadMatrixBool(SEXP R_mtxSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type R_mtx(R_mtxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadMatrixBool(R_mtx, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadMatrixInt
void UploadMatrixInt(IntegerMatrix R_mtx, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadMatrixInt(SEXP R_mtxSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type R_mtx(R_mtxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadMatrixInt(R_mtx, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadMatrixDouble
void UploadMatrixDouble(NumericMatrix R_mtx, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadMatrixDouble(SEXP R_mtxSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type R_mtx(R_mtxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadMatrixDouble(R_mtx, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadVectorSymbol
void UploadVectorSymbol(IntegerVector R_vec);
RcppExport SEXP _RDolphinDB_UploadVectorSymbol(SEXP R_vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type R_vec(R_vecSEXP);
    UploadVectorSymbol(R_vec);
    return R_NilValue;
END_RCPP
}
// UploadVectorString
void UploadVectorString(CharacterVector R_vec, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadVectorString(SEXP R_vecSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type R_vec(R_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadVectorString(R_vec, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadVectorDouble
void UploadVectorDouble(NumericVector R_vec, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadVectorDouble(SEXP R_vecSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type R_vec(R_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadVectorDouble(R_vec, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadVectorBool
void UploadVectorBool(LogicalVector R_vec, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadVectorBool(SEXP R_vecSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type R_vec(R_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadVectorBool(R_vec, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadVectorInt
void UploadVectorInt(IntegerVector R_vec, IntegerVector R_NAIndex);
RcppExport SEXP _RDolphinDB_UploadVectorInt(SEXP R_vecSEXP, SEXP R_NAIndexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type R_vec(R_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R_NAIndex(R_NAIndexSEXP);
    UploadVectorInt(R_vec, R_NAIndex);
    return R_NilValue;
END_RCPP
}
// UploadVectorNULL
void UploadVectorNULL(int row, int clm);
RcppExport SEXP _RDolphinDB_UploadVectorNULL(SEXP rowSEXP, SEXP clmSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type clm(clmSEXP);
    UploadVectorNULL(row, clm);
    return R_NilValue;
END_RCPP
}
// UploadScalarInt
void UploadScalarInt(int val);
RcppExport SEXP _RDolphinDB_UploadScalarInt(SEXP valSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type val(valSEXP);
    UploadScalarInt(val);
    return R_NilValue;
END_RCPP
}
// UploadScalarBool
void UploadScalarBool(bool val);
RcppExport SEXP _RDolphinDB_UploadScalarBool(SEXP valSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type val(valSEXP);
    UploadScalarBool(val);
    return R_NilValue;
END_RCPP
}
// UploadScalarNULL
void UploadScalarNULL();
RcppExport SEXP _RDolphinDB_UploadScalarNULL() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    UploadScalarNULL();
    return R_NilValue;
END_RCPP
}
// UploadScalarDouble
void UploadScalarDouble(double val);
RcppExport SEXP _RDolphinDB_UploadScalarDouble(SEXP valSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type val(valSEXP);
    UploadScalarDouble(val);
    return R_NilValue;
END_RCPP
}
// UploadScalarString
void UploadScalarString(String val);
RcppExport SEXP _RDolphinDB_UploadScalarString(SEXP valSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type val(valSEXP);
    UploadScalarString(val);
    return R_NilValue;
END_RCPP
}
// Clear
void Clear();
RcppExport SEXP _RDolphinDB_Clear() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Clear();
    return R_NilValue;
END_RCPP
}
// DisConnect
void DisConnect();
RcppExport SEXP _RDolphinDB_DisConnect() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    DisConnect();
    return R_NilValue;
END_RCPP
}
// ReturnAnyVectorTypelist
IntegerVector ReturnAnyVectorTypelist();
RcppExport SEXP _RDolphinDB_ReturnAnyVectorTypelist() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ReturnAnyVectorTypelist());
    return rcpp_result_gen;
END_RCPP
}
// ReturnScalarNA
bool ReturnScalarNA(int index);
RcppExport SEXP _RDolphinDB_ReturnScalarNA(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnScalarNA(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnScalarBool
bool ReturnScalarBool(int index);
RcppExport SEXP _RDolphinDB_ReturnScalarBool(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnScalarBool(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnScalarInt
int ReturnScalarInt(int index);
RcppExport SEXP _RDolphinDB_ReturnScalarInt(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnScalarInt(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnScalarDouble
double ReturnScalarDouble(int index);
RcppExport SEXP _RDolphinDB_ReturnScalarDouble(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnScalarDouble(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnScalarString
String ReturnScalarString(int index);
RcppExport SEXP _RDolphinDB_ReturnScalarString(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnScalarString(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnScalarTime
NumericVector ReturnScalarTime(int index);
RcppExport SEXP _RDolphinDB_ReturnScalarTime(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnScalarTime(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnScalarDate
NumericVector ReturnScalarDate(int index);
RcppExport SEXP _RDolphinDB_ReturnScalarDate(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnScalarDate(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnVectorBool
LogicalVector ReturnVectorBool(int index);
RcppExport SEXP _RDolphinDB_ReturnVectorBool(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnVectorBool(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnVectorFactor
IntegerVector ReturnVectorFactor(int index);
RcppExport SEXP _RDolphinDB_ReturnVectorFactor(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnVectorFactor(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnVectorInt
IntegerVector ReturnVectorInt(int index);
RcppExport SEXP _RDolphinDB_ReturnVectorInt(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnVectorInt(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnVectorDouble
NumericVector ReturnVectorDouble(int index);
RcppExport SEXP _RDolphinDB_ReturnVectorDouble(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnVectorDouble(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnVectorString
CharacterVector ReturnVectorString(int index);
RcppExport SEXP _RDolphinDB_ReturnVectorString(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnVectorString(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnVectorDate
DateVector ReturnVectorDate(int index);
RcppExport SEXP _RDolphinDB_ReturnVectorDate(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnVectorDate(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnVectorTime
NumericVector ReturnVectorTime(int index);
RcppExport SEXP _RDolphinDB_ReturnVectorTime(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnVectorTime(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnVectorNAIndex
IntegerVector ReturnVectorNAIndex(int index);
RcppExport SEXP _RDolphinDB_ReturnVectorNAIndex(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnVectorNAIndex(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixHasLable
bool ReturnMatrixHasLable(bool row, int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixHasLable(SEXP rowSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixHasLable(row, index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixLableType
int ReturnMatrixLableType(bool row, int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixLableType(SEXP rowSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixLableType(row, index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixLableNAIndex
IntegerVector ReturnMatrixLableNAIndex(bool row, int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixLableNAIndex(SEXP rowSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixLableNAIndex(row, index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixVectorBoolLable
LogicalVector ReturnMatrixVectorBoolLable(bool row, int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixVectorBoolLable(SEXP rowSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixVectorBoolLable(row, index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixVectorIntLable
IntegerVector ReturnMatrixVectorIntLable(bool row, int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixVectorIntLable(SEXP rowSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixVectorIntLable(row, index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixVectorDoubleLable
NumericVector ReturnMatrixVectorDoubleLable(bool row, int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixVectorDoubleLable(SEXP rowSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixVectorDoubleLable(row, index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixVectorStringLable
CharacterVector ReturnMatrixVectorStringLable(bool row, int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixVectorStringLable(SEXP rowSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixVectorStringLable(row, index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixBool
LogicalMatrix ReturnMatrixBool(int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixBool(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixBool(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixInt
IntegerMatrix ReturnMatrixInt(int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixInt(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixInt(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixDouble
NumericMatrix ReturnMatrixDouble(int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixDouble(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixDouble(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixString
CharacterMatrix ReturnMatrixString(int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixString(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixString(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnMatrixNAIndex
IntegerVector ReturnMatrixNAIndex(int index);
RcppExport SEXP _RDolphinDB_ReturnMatrixNAIndex(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnMatrixNAIndex(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnType
IntegerVector ReturnTableColumnType(int index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnType(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnType(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumeName
CharacterVector ReturnTableColumeName(int index);
RcppExport SEXP _RDolphinDB_ReturnTableColumeName(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumeName(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnEmptyDataFrame
DataFrame ReturnEmptyDataFrame(int index);
RcppExport SEXP _RDolphinDB_ReturnEmptyDataFrame(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnEmptyDataFrame(index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnLogical
LogicalVector ReturnTableColumnLogical(int index, int entity_index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnLogical(SEXP indexSEXP, SEXP entity_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type entity_index(entity_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnLogical(index, entity_index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnFactor
IntegerVector ReturnTableColumnFactor(int index, int entity_index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnFactor(SEXP indexSEXP, SEXP entity_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type entity_index(entity_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnFactor(index, entity_index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnInteger
IntegerVector ReturnTableColumnInteger(int index, int entity_index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnInteger(SEXP indexSEXP, SEXP entity_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type entity_index(entity_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnInteger(index, entity_index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnDouble
NumericVector ReturnTableColumnDouble(int index, int entity_index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnDouble(SEXP indexSEXP, SEXP entity_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type entity_index(entity_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnDouble(index, entity_index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnTime
NumericVector ReturnTableColumnTime(int index, int entity_index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnTime(SEXP indexSEXP, SEXP entity_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type entity_index(entity_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnTime(index, entity_index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnDate
DateVector ReturnTableColumnDate(int index, int entity_index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnDate(SEXP indexSEXP, SEXP entity_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type entity_index(entity_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnDate(index, entity_index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnString
CharacterVector ReturnTableColumnString(int index, int entity_index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnString(SEXP indexSEXP, SEXP entity_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type entity_index(entity_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnString(index, entity_index));
    return rcpp_result_gen;
END_RCPP
}
// ReturnTableColumnNAIndex
IntegerVector ReturnTableColumnNAIndex(int index, int entity_index);
RcppExport SEXP _RDolphinDB_ReturnTableColumnNAIndex(SEXP indexSEXP, SEXP entity_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type entity_index(entity_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnTableColumnNAIndex(index, entity_index));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RDolphinDB_Connect", (DL_FUNC) &_RDolphinDB_Connect, 2},
    {"_RDolphinDB_RunScript", (DL_FUNC) &_RDolphinDB_RunScript, 1},
    {"_RDolphinDB_RunFunctionInit", (DL_FUNC) &_RDolphinDB_RunFunctionInit, 2},
    {"_RDolphinDB_RunUploadInit", (DL_FUNC) &_RDolphinDB_RunUploadInit, 1},
    {"_RDolphinDB_ReceiveHeader", (DL_FUNC) &_RDolphinDB_ReceiveHeader, 0},
    {"_RDolphinDB_ReceiveEntity", (DL_FUNC) &_RDolphinDB_ReceiveEntity, 0},
    {"_RDolphinDB_UploadVectorDateTime", (DL_FUNC) &_RDolphinDB_UploadVectorDateTime, 2},
    {"_RDolphinDB_UploadScalarDateTime", (DL_FUNC) &_RDolphinDB_UploadScalarDateTime, 1},
    {"_RDolphinDB_UploadVectorDate", (DL_FUNC) &_RDolphinDB_UploadVectorDate, 2},
    {"_RDolphinDB_UploadScalarDate", (DL_FUNC) &_RDolphinDB_UploadScalarDate, 1},
    {"_RDolphinDB_UploadTableBasic", (DL_FUNC) &_RDolphinDB_UploadTableBasic, 3},
    {"_RDolphinDB_UploadMatrixNULL", (DL_FUNC) &_RDolphinDB_UploadMatrixNULL, 2},
    {"_RDolphinDB_UploadMatrixLableFlag", (DL_FUNC) &_RDolphinDB_UploadMatrixLableFlag, 1},
    {"_RDolphinDB_UploadMatrixFlag", (DL_FUNC) &_RDolphinDB_UploadMatrixFlag, 1},
    {"_RDolphinDB_UploadMatrixBool", (DL_FUNC) &_RDolphinDB_UploadMatrixBool, 2},
    {"_RDolphinDB_UploadMatrixInt", (DL_FUNC) &_RDolphinDB_UploadMatrixInt, 2},
    {"_RDolphinDB_UploadMatrixDouble", (DL_FUNC) &_RDolphinDB_UploadMatrixDouble, 2},
    {"_RDolphinDB_UploadVectorSymbol", (DL_FUNC) &_RDolphinDB_UploadVectorSymbol, 1},
    {"_RDolphinDB_UploadVectorString", (DL_FUNC) &_RDolphinDB_UploadVectorString, 2},
    {"_RDolphinDB_UploadVectorDouble", (DL_FUNC) &_RDolphinDB_UploadVectorDouble, 2},
    {"_RDolphinDB_UploadVectorBool", (DL_FUNC) &_RDolphinDB_UploadVectorBool, 2},
    {"_RDolphinDB_UploadVectorInt", (DL_FUNC) &_RDolphinDB_UploadVectorInt, 2},
    {"_RDolphinDB_UploadVectorNULL", (DL_FUNC) &_RDolphinDB_UploadVectorNULL, 2},
    {"_RDolphinDB_UploadScalarInt", (DL_FUNC) &_RDolphinDB_UploadScalarInt, 1},
    {"_RDolphinDB_UploadScalarBool", (DL_FUNC) &_RDolphinDB_UploadScalarBool, 1},
    {"_RDolphinDB_UploadScalarNULL", (DL_FUNC) &_RDolphinDB_UploadScalarNULL, 0},
    {"_RDolphinDB_UploadScalarDouble", (DL_FUNC) &_RDolphinDB_UploadScalarDouble, 1},
    {"_RDolphinDB_UploadScalarString", (DL_FUNC) &_RDolphinDB_UploadScalarString, 1},
    {"_RDolphinDB_Clear", (DL_FUNC) &_RDolphinDB_Clear, 0},
    {"_RDolphinDB_DisConnect", (DL_FUNC) &_RDolphinDB_DisConnect, 0},
    {"_RDolphinDB_ReturnAnyVectorTypelist", (DL_FUNC) &_RDolphinDB_ReturnAnyVectorTypelist, 0},
    {"_RDolphinDB_ReturnScalarNA", (DL_FUNC) &_RDolphinDB_ReturnScalarNA, 1},
    {"_RDolphinDB_ReturnScalarBool", (DL_FUNC) &_RDolphinDB_ReturnScalarBool, 1},
    {"_RDolphinDB_ReturnScalarInt", (DL_FUNC) &_RDolphinDB_ReturnScalarInt, 1},
    {"_RDolphinDB_ReturnScalarDouble", (DL_FUNC) &_RDolphinDB_ReturnScalarDouble, 1},
    {"_RDolphinDB_ReturnScalarString", (DL_FUNC) &_RDolphinDB_ReturnScalarString, 1},
    {"_RDolphinDB_ReturnScalarTime", (DL_FUNC) &_RDolphinDB_ReturnScalarTime, 1},
    {"_RDolphinDB_ReturnScalarDate", (DL_FUNC) &_RDolphinDB_ReturnScalarDate, 1},
    {"_RDolphinDB_ReturnVectorBool", (DL_FUNC) &_RDolphinDB_ReturnVectorBool, 1},
    {"_RDolphinDB_ReturnVectorFactor", (DL_FUNC) &_RDolphinDB_ReturnVectorFactor, 1},
    {"_RDolphinDB_ReturnVectorInt", (DL_FUNC) &_RDolphinDB_ReturnVectorInt, 1},
    {"_RDolphinDB_ReturnVectorDouble", (DL_FUNC) &_RDolphinDB_ReturnVectorDouble, 1},
    {"_RDolphinDB_ReturnVectorString", (DL_FUNC) &_RDolphinDB_ReturnVectorString, 1},
    {"_RDolphinDB_ReturnVectorDate", (DL_FUNC) &_RDolphinDB_ReturnVectorDate, 1},
    {"_RDolphinDB_ReturnVectorTime", (DL_FUNC) &_RDolphinDB_ReturnVectorTime, 1},
    {"_RDolphinDB_ReturnVectorNAIndex", (DL_FUNC) &_RDolphinDB_ReturnVectorNAIndex, 1},
    {"_RDolphinDB_ReturnMatrixHasLable", (DL_FUNC) &_RDolphinDB_ReturnMatrixHasLable, 2},
    {"_RDolphinDB_ReturnMatrixLableType", (DL_FUNC) &_RDolphinDB_ReturnMatrixLableType, 2},
    {"_RDolphinDB_ReturnMatrixLableNAIndex", (DL_FUNC) &_RDolphinDB_ReturnMatrixLableNAIndex, 2},
    {"_RDolphinDB_ReturnMatrixVectorBoolLable", (DL_FUNC) &_RDolphinDB_ReturnMatrixVectorBoolLable, 2},
    {"_RDolphinDB_ReturnMatrixVectorIntLable", (DL_FUNC) &_RDolphinDB_ReturnMatrixVectorIntLable, 2},
    {"_RDolphinDB_ReturnMatrixVectorDoubleLable", (DL_FUNC) &_RDolphinDB_ReturnMatrixVectorDoubleLable, 2},
    {"_RDolphinDB_ReturnMatrixVectorStringLable", (DL_FUNC) &_RDolphinDB_ReturnMatrixVectorStringLable, 2},
    {"_RDolphinDB_ReturnMatrixBool", (DL_FUNC) &_RDolphinDB_ReturnMatrixBool, 1},
    {"_RDolphinDB_ReturnMatrixInt", (DL_FUNC) &_RDolphinDB_ReturnMatrixInt, 1},
    {"_RDolphinDB_ReturnMatrixDouble", (DL_FUNC) &_RDolphinDB_ReturnMatrixDouble, 1},
    {"_RDolphinDB_ReturnMatrixString", (DL_FUNC) &_RDolphinDB_ReturnMatrixString, 1},
    {"_RDolphinDB_ReturnMatrixNAIndex", (DL_FUNC) &_RDolphinDB_ReturnMatrixNAIndex, 1},
    {"_RDolphinDB_ReturnTableColumnType", (DL_FUNC) &_RDolphinDB_ReturnTableColumnType, 1},
    {"_RDolphinDB_ReturnTableColumeName", (DL_FUNC) &_RDolphinDB_ReturnTableColumeName, 1},
    {"_RDolphinDB_ReturnEmptyDataFrame", (DL_FUNC) &_RDolphinDB_ReturnEmptyDataFrame, 1},
    {"_RDolphinDB_ReturnTableColumnLogical", (DL_FUNC) &_RDolphinDB_ReturnTableColumnLogical, 2},
    {"_RDolphinDB_ReturnTableColumnFactor", (DL_FUNC) &_RDolphinDB_ReturnTableColumnFactor, 2},
    {"_RDolphinDB_ReturnTableColumnInteger", (DL_FUNC) &_RDolphinDB_ReturnTableColumnInteger, 2},
    {"_RDolphinDB_ReturnTableColumnDouble", (DL_FUNC) &_RDolphinDB_ReturnTableColumnDouble, 2},
    {"_RDolphinDB_ReturnTableColumnTime", (DL_FUNC) &_RDolphinDB_ReturnTableColumnTime, 2},
    {"_RDolphinDB_ReturnTableColumnDate", (DL_FUNC) &_RDolphinDB_ReturnTableColumnDate, 2},
    {"_RDolphinDB_ReturnTableColumnString", (DL_FUNC) &_RDolphinDB_ReturnTableColumnString, 2},
    {"_RDolphinDB_ReturnTableColumnNAIndex", (DL_FUNC) &_RDolphinDB_ReturnTableColumnNAIndex, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RDolphinDB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
