# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Connect <- function(host, port) {
    .Call('_RDolphinDB_Connect', PACKAGE = 'RDolphinDB', host, port)
}

RunScript <- function(script) {
    .Call('_RDolphinDB_RunScript', PACKAGE = 'RDolphinDB', script)
}

RunFunctionInit <- function(func, arg_size) {
    .Call('_RDolphinDB_RunFunctionInit', PACKAGE = 'RDolphinDB', func, arg_size)
}

RunUploadInit <- function(R_keys) {
    .Call('_RDolphinDB_RunUploadInit', PACKAGE = 'RDolphinDB', R_keys)
}

ReceiveHeader <- function() {
    .Call('_RDolphinDB_ReceiveHeader', PACKAGE = 'RDolphinDB')
}

ReceiveEntity <- function() {
    .Call('_RDolphinDB_ReceiveEntity', PACKAGE = 'RDolphinDB')
}

UploadVectorDateTime <- function(R_vec, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadVectorDateTime', PACKAGE = 'RDolphinDB', R_vec, R_NAIndex))
}

UploadScalarDateTime <- function(date_time_str) {
    invisible(.Call('_RDolphinDB_UploadScalarDateTime', PACKAGE = 'RDolphinDB', date_time_str))
}

UploadVectorDate <- function(R_vec, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadVectorDate', PACKAGE = 'RDolphinDB', R_vec, R_NAIndex))
}

UploadScalarDate <- function(date_str) {
    invisible(.Call('_RDolphinDB_UploadScalarDate', PACKAGE = 'RDolphinDB', date_str))
}

UploadTableBasic <- function(row, clm, Colnames) {
    invisible(.Call('_RDolphinDB_UploadTableBasic', PACKAGE = 'RDolphinDB', row, clm, Colnames))
}

UploadMatrixNULL <- function(row, clm) {
    invisible(.Call('_RDolphinDB_UploadMatrixNULL', PACKAGE = 'RDolphinDB', row, clm))
}

UploadMatrixLableFlag <- function(flag) {
    invisible(.Call('_RDolphinDB_UploadMatrixLableFlag', PACKAGE = 'RDolphinDB', flag))
}

UploadMatrixFlag <- function(flag) {
    invisible(.Call('_RDolphinDB_UploadMatrixFlag', PACKAGE = 'RDolphinDB', flag))
}

UploadMatrixBool <- function(R_mtx, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadMatrixBool', PACKAGE = 'RDolphinDB', R_mtx, R_NAIndex))
}

UploadMatrixInt <- function(R_mtx, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadMatrixInt', PACKAGE = 'RDolphinDB', R_mtx, R_NAIndex))
}

UploadMatrixDouble <- function(R_mtx, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadMatrixDouble', PACKAGE = 'RDolphinDB', R_mtx, R_NAIndex))
}

UploadVectorString <- function(R_vec, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadVectorString', PACKAGE = 'RDolphinDB', R_vec, R_NAIndex))
}

UploadVectorDouble <- function(R_vec, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadVectorDouble', PACKAGE = 'RDolphinDB', R_vec, R_NAIndex))
}

UploadVectorBool <- function(R_vec, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadVectorBool', PACKAGE = 'RDolphinDB', R_vec, R_NAIndex))
}

UploadVectorInt <- function(R_vec, R_NAIndex) {
    invisible(.Call('_RDolphinDB_UploadVectorInt', PACKAGE = 'RDolphinDB', R_vec, R_NAIndex))
}

UploadVectorNULL <- function(row, clm) {
    invisible(.Call('_RDolphinDB_UploadVectorNULL', PACKAGE = 'RDolphinDB', row, clm))
}

UploadScalarInt <- function(val) {
    invisible(.Call('_RDolphinDB_UploadScalarInt', PACKAGE = 'RDolphinDB', val))
}

UploadScalarBool <- function(val) {
    invisible(.Call('_RDolphinDB_UploadScalarBool', PACKAGE = 'RDolphinDB', val))
}

UploadScalarNULL <- function() {
    invisible(.Call('_RDolphinDB_UploadScalarNULL', PACKAGE = 'RDolphinDB'))
}

UploadScalarDouble <- function(val) {
    invisible(.Call('_RDolphinDB_UploadScalarDouble', PACKAGE = 'RDolphinDB', val))
}

UploadScalarString <- function(val) {
    invisible(.Call('_RDolphinDB_UploadScalarString', PACKAGE = 'RDolphinDB', val))
}

Clear <- function() {
    invisible(.Call('_RDolphinDB_Clear', PACKAGE = 'RDolphinDB'))
}

DisConnect <- function() {
    invisible(.Call('_RDolphinDB_DisConnect', PACKAGE = 'RDolphinDB'))
}

ReturnScalarNA <- function() {
    .Call('_RDolphinDB_ReturnScalarNA', PACKAGE = 'RDolphinDB')
}

ReturnScalarBool <- function() {
    .Call('_RDolphinDB_ReturnScalarBool', PACKAGE = 'RDolphinDB')
}

ReturnScalarInt <- function() {
    .Call('_RDolphinDB_ReturnScalarInt', PACKAGE = 'RDolphinDB')
}

ReturnScalarDouble <- function() {
    .Call('_RDolphinDB_ReturnScalarDouble', PACKAGE = 'RDolphinDB')
}

ReturnScalarString <- function() {
    .Call('_RDolphinDB_ReturnScalarString', PACKAGE = 'RDolphinDB')
}

ReturnVectorBool <- function() {
    .Call('_RDolphinDB_ReturnVectorBool', PACKAGE = 'RDolphinDB')
}

ReturnVectorInt <- function() {
    .Call('_RDolphinDB_ReturnVectorInt', PACKAGE = 'RDolphinDB')
}

ReturnVectorDouble <- function() {
    .Call('_RDolphinDB_ReturnVectorDouble', PACKAGE = 'RDolphinDB')
}

ReturnVectorString <- function() {
    .Call('_RDolphinDB_ReturnVectorString', PACKAGE = 'RDolphinDB')
}

ReturnVectorNAIndex <- function() {
    .Call('_RDolphinDB_ReturnVectorNAIndex', PACKAGE = 'RDolphinDB')
}

ReturnMatrixHasLable <- function(row) {
    .Call('_RDolphinDB_ReturnMatrixHasLable', PACKAGE = 'RDolphinDB', row)
}

ReturnMatrixLableType <- function(row) {
    .Call('_RDolphinDB_ReturnMatrixLableType', PACKAGE = 'RDolphinDB', row)
}

ReturnMatrixLableNAIndex <- function(row) {
    .Call('_RDolphinDB_ReturnMatrixLableNAIndex', PACKAGE = 'RDolphinDB', row)
}

ReturnMatrixVectorBoolLable <- function(row) {
    .Call('_RDolphinDB_ReturnMatrixVectorBoolLable', PACKAGE = 'RDolphinDB', row)
}

ReturnMatrixVectorIntLable <- function(row) {
    .Call('_RDolphinDB_ReturnMatrixVectorIntLable', PACKAGE = 'RDolphinDB', row)
}

ReturnMatrixVectorDoubleLable <- function(row) {
    .Call('_RDolphinDB_ReturnMatrixVectorDoubleLable', PACKAGE = 'RDolphinDB', row)
}

ReturnMatrixVectorStringLable <- function(row) {
    .Call('_RDolphinDB_ReturnMatrixVectorStringLable', PACKAGE = 'RDolphinDB', row)
}

ReturnMatrixBool <- function() {
    .Call('_RDolphinDB_ReturnMatrixBool', PACKAGE = 'RDolphinDB')
}

ReturnMatrixInt <- function() {
    .Call('_RDolphinDB_ReturnMatrixInt', PACKAGE = 'RDolphinDB')
}

ReturnMatrixDouble <- function() {
    .Call('_RDolphinDB_ReturnMatrixDouble', PACKAGE = 'RDolphinDB')
}

ReturnMatrixString <- function() {
    .Call('_RDolphinDB_ReturnMatrixString', PACKAGE = 'RDolphinDB')
}

ReturnMatrixNAIndex <- function() {
    .Call('_RDolphinDB_ReturnMatrixNAIndex', PACKAGE = 'RDolphinDB')
}

ReturnTableColumnType <- function() {
    .Call('_RDolphinDB_ReturnTableColumnType', PACKAGE = 'RDolphinDB')
}

ReturnTableColumeName <- function() {
    .Call('_RDolphinDB_ReturnTableColumeName', PACKAGE = 'RDolphinDB')
}

ReturnEmptyDataFrame <- function() {
    .Call('_RDolphinDB_ReturnEmptyDataFrame', PACKAGE = 'RDolphinDB')
}

ReturnTableColumnLogical <- function(index) {
    .Call('_RDolphinDB_ReturnTableColumnLogical', PACKAGE = 'RDolphinDB', index)
}

ReturnTableColumnInteger <- function(index) {
    .Call('_RDolphinDB_ReturnTableColumnInteger', PACKAGE = 'RDolphinDB', index)
}

ReturnTableColumnDouble <- function(index) {
    .Call('_RDolphinDB_ReturnTableColumnDouble', PACKAGE = 'RDolphinDB', index)
}

ReturnTableColumnString <- function(index) {
    .Call('_RDolphinDB_ReturnTableColumnString', PACKAGE = 'RDolphinDB', index)
}

ReturnTableColumnNAIndex <- function(index) {
    .Call('_RDolphinDB_ReturnTableColumnNAIndex', PACKAGE = 'RDolphinDB', index)
}

